# Generated by Django 6.0.4 on 2026-05-07 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=20)),
                ('father_email', models.EmailField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_mobile', models.CharField(max_length=20)),
                ('mother_email', models.EmailField(max_length=100)),
                ('present_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Student_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('student_class', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('section', models.CharField(max_length=15)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='fotos/students/')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.parent')),
            ],
        ),
    ]
