# Generated by Django 6.0.4 on 2026-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_student_id_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='permanent_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
