# Generated by Django 6.0.4 on 2026-05-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='rYrnASiz10nw4s6bHXU2hi1ERlJQutDz', editable=False, max_length=32, unique=True),
        ),
    ]
